name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        env:
          DEPLOY_PATH: /home/marcosgardinali/coder-challenge-2025
          SSH_USER: marcosgardinali
          SERVER_IP: 172.210.234.104
        run: |
          # Criar diretório se não existir
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SERVER_IP "mkdir -p $DEPLOY_PATH"
          
          # Copiar arquivos
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'node_modules' \
            --exclude '.env' \
            ./ $SSH_USER@$SERVER_IP:$DEPLOY_PATH/

      - name: Create .env files
        env:
          SSH_USER: marcosgardinali
          SERVER_IP: 172.210.234.104
          DEPLOY_PATH: /home/marcosgardinali/coder-challenge-2025
          ENV_BACKEND: ${{ secrets.ENV_BACKEND }}
          ENV_FRONTEND: ${{ secrets.ENV_FRONTEND }}
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SERVER_IP "echo '${ENV_BACKEND}' > ${DEPLOY_PATH}/backend/.env"
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SERVER_IP "echo '${ENV_FRONTEND}' > ${DEPLOY_PATH}/frontend/.env"

      - name: Build and restart containers
        env:
          SSH_USER: marcosgardinali
          SERVER_IP: 172.210.234.104
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SERVER_IP 'cd /home/marcosgardinali/coder-challenge-2025 && \
          docker compose down && \
          docker compose up --build -d'